-- Tabela de Pedidos de Compra
-- Registra quando itens são solicitados ao setor de compras

CREATE TABLE IF NOT EXISTS pedidos_compra (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  item_id BIGINT REFERENCES itens(id) ON DELETE CASCADE NOT NULL,
  nota_id BIGINT REFERENCES notas(id) ON DELETE CASCADE,
  quantidade_solicitada NUMERIC NOT NULL,
  data_solicitacao TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  usuario_solicitante TEXT,
  status TEXT DEFAULT 'AGUARDANDO', -- AGUARDANDO, EM_ANDAMENTO, CONCLUIDO
  observacoes TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Habilitar RLS
ALTER TABLE pedidos_compra ENABLE ROW LEVEL SECURITY;

-- Política de acesso (Dev)
CREATE POLICY "Acesso Total Pedidos Compra" ON pedidos_compra FOR ALL USING (true) WITH CHECK (true);

-- Comentários
COMMENT ON TABLE pedidos_compra IS 'Registros de solicitações de compra para itens pendentes';
COMMENT ON COLUMN pedidos_compra.status IS 'Status da solicitação: AGUARDANDO, EM_ANDAMENTO, CONCLUIDO';
