-- 1. Tabela de Cargos e Permissões
CREATE TABLE IF NOT EXISTS cargos_permissoes (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nome TEXT NOT NULL UNIQUE,
    permissoes JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Atualizar Profiles com Cargo e Controle de Sessão
ALTER TABLE profiles 
ADD COLUMN IF NOT EXISTS cargo_id BIGINT REFERENCES cargos_permissoes(id),
ADD COLUMN IF NOT EXISTS last_password_change TIMESTAMPTZ DEFAULT NOW();

-- 3. Inserir Cargos Padrão (Opcional, para facilitar)
INSERT INTO cargos_permissoes (nome, permissoes)
VALUES 
('Dono/DEV', '{"all": true}'),
('Administrador', '{"dashboard": true, "empenhos": "full", "compras": "full", "config": true}'),
('Operacional', '{"dashboard": true, "empenhos": "view", "logistica": "execute", "tarefas": true}')
ON CONFLICT (nome) DO NOTHING;

-- 4. Criar política de leitura para Cargos
ALTER TABLE cargos_permissoes ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Leitura pública de cargos" ON cargos_permissoes FOR SELECT USING (true);
CREATE POLICY "Gestão de cargos pelo DEV" ON cargos_permissoes 
FOR ALL USING (
    EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND nivel = 'DEV')
);
