-- Recreate catalogo_produtos table with the 9 selected columns
DROP TABLE IF EXISTS public.catalogo_produtos CASCADE;

CREATE TABLE public.catalogo_produtos (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo_interno text UNIQUE NOT NULL,
    descricao_completa text NOT NULL,
    descricao_resumida text,
    unidade_venda text,
    unidade_compra text,
    marca text,
    fabricante text,
    grupo text,
    classe text,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE public.catalogo_produtos ENABLE ROW LEVEL SECURITY;

-- Allow SELECT for all authenticated users (so buyers/sellers can query it for autocomplete)
CREATE POLICY "Permitir leitura para todos autenticados" ON public.catalogo_produtos
    FOR SELECT TO authenticated USING (true);

-- Allow ALL (insert, update, delete, select) for DEV role
CREATE POLICY "Permitir gerenciamento completo para DEV" ON public.catalogo_produtos
    FOR ALL TO authenticated
    USING (
        EXISTS (
            SELECT 1 FROM public.profiles
            WHERE profiles.id = auth.uid() AND profiles.nivel = 'DEV'
        )
    )
    WITH CHECK (
        EXISTS (
            SELECT 1 FROM public.profiles
            WHERE profiles.id = auth.uid() AND profiles.nivel = 'DEV'
        )
    );
